// <auto-generated />
using System;
using AStar.Dev.OneDrive.Sync.Client.Infrastructure.Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStar.Dev.OneDrive.Sync.Client.Migrations
{
    [DbContext(typeof(OneDriveSyncDbContext))]
    partial class OneDriveSyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DebugLoggingEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("HashedAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeSyncDirectory")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int?>("MaxBandwidthKBps")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConcurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(5);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HashedEmail")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.ApplicationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedAccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("LogLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceContext")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("LogLevel")
                        .HasDatabaseName("idx_applicationlogs_loglevel");

                    b.HasIndex("HashedAccountId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_applicationlogs_hashedaccountid_timestamp");

                    b.ToTable("ApplicationLogs");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.ConflictLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConflictType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HashedAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LocalLastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemoteLastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResolutionAction")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("ConflictLogs");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.DeltaToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("DeltaTokens");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.DiagnosticSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("LogLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HashedAccountId")
                        .IsUnique();

                    b.ToTable("DiagnosticSettings");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.FileSystemItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<int>("LastSyncDirection")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LocalModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RemoteModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("HashedAccountId");

                    b.ToTable("FileSystemItems");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.SyncHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedAccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ItemsDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemsUploaded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncDirection")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncResult")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncHistory");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.ApplicationLog", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Sync.Client.Common.Models.Account", null)
                        .WithMany("ApplicationLogs")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.ConflictLog", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Sync.Client.Common.Models.Account", null)
                        .WithMany("ConflictLogs")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.DeltaToken", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Sync.Client.Common.Models.Account", null)
                        .WithMany("DeltaTokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.FileSystemItem", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Sync.Client.Common.Models.Account", null)
                        .WithMany("FileSystemItems")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.Account", b =>
                {
                    b.Navigation("ApplicationLogs");

                    b.Navigation("ConflictLogs");

                    b.Navigation("DeltaTokens");

                    b.Navigation("FileSystemItems");
                });
#pragma warning restore 612, 618
        }
    }
}
