// <auto-generated />
using System;
using AStarOneDriveClient.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStarOneDriveClient.Migrations
{
    [DbContext(typeof(SyncDbContext))]
    [Migration("20260105204114_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.AccountEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeltaToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAuthenticated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalSyncPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.HasIndex("LocalSyncPath")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.FileMetadataEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("ETag")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastSyncDirection")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountId", "Path");

                    b.ToTable("FileMetadata");
                });

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.SyncConfigurationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "FolderPath");

                    b.ToTable("SyncConfigurations");
                });

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.SyncStateEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CompletedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompletedFiles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConflictsDetected")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstimatedSecondsRemaining")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesDownloading")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesUploading")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpdateUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("MegabytesPerSecond")
                        .HasColumnType("REAL");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.WindowPreferencesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(600.0);

                    b.Property<bool>("IsMaximized")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Width")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(800.0);

                    b.Property<double?>("X")
                        .HasColumnType("REAL");

                    b.Property<double?>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WindowPreferences");
                });

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.FileMetadataEntity", b =>
                {
                    b.HasOne("AStarOneDriveClient.Data.Entities.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.SyncConfigurationEntity", b =>
                {
                    b.HasOne("AStarOneDriveClient.Data.Entities.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.SyncStateEntity", b =>
                {
                    b.HasOne("AStarOneDriveClient.Data.Entities.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
