// <auto-generated />
using System;
using AStarOneDriveClient.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStarOneDriveClient.Migrations
{
    [DbContext(typeof(SyncDbContext))]
    partial class SyncDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.AccountEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AutoSyncIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeltaToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableDebugLogging")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableDetailedSyncLogging")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAuthenticated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalSyncPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxItemsInBatch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxParallelUpDownloads")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.HasIndex("LocalSyncPath")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.DebugLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DebugLogs");
                });

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.FileMetadataEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("ETag")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastSyncDirection")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountId", "Path");

                    b.ToTable("FileMetadata");
                });

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.FileOperationLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OneDriveId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Operation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileOperationLogs");
                });

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.SyncConfigurationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FolderPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "FolderPath");

                    b.ToTable("SyncConfigurations");
                });

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.SyncConflictEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LocalModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("LocalSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RemoteModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("RemoteSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResolutionStrategy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountId", "IsResolved");

                    b.ToTable("SyncConflicts");
                });

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.SyncSessionLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConflictsDetected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesUploaded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncSessionLogs");
                });

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.WindowPreferencesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(600.0);

                    b.Property<bool>("IsMaximized")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Width")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(800.0);

                    b.Property<double?>("X")
                        .HasColumnType("REAL");

                    b.Property<double?>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WindowPreferences");
                });

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.FileMetadataEntity", b =>
                {
                    b.HasOne("AStarOneDriveClient.Data.Entities.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.SyncConfigurationEntity", b =>
                {
                    b.HasOne("AStarOneDriveClient.Data.Entities.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStarOneDriveClient.Data.Entities.SyncConflictEntity", b =>
                {
                    b.HasOne("AStarOneDriveClient.Data.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
