// <auto-generated />
using System;
using AStar.Dev.OneDrive.Sync.Client.Infrastructure.Database.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AStar.Dev.OneDrive.Sync.Client.Infrastructure.Database.Migrations
{
    [DbContext(typeof(OneDriveSyncDbContext))]
    [Migration("20260204131813_UpdatePropertyTypes")]
    partial class UpdatePropertyTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("onedrive")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool>("EnableDebugLogging")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("HashedEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HomeSyncDirectory")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAuthRefresh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxConcurrentDownloads")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<int>("MaxConcurrentUploads")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<string>("TokenStorageKey")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HashedEmail")
                        .IsUnique();

                    b.ToTable("Accounts", "onedrive");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.ApplicationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AccountId")
                        .HasColumnType("text");

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<int>("LogLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceContext")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("LogLevel")
                        .HasDatabaseName("idx_applicationlogs_loglevel");

                    b.HasIndex("AccountId", "Timestamp")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_applicationlogs_accountid_timestamp");

                    b.ToTable("ApplicationLogs", "onedrive");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.ConflictLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ConflictType")
                        .HasColumnType("integer");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LocalLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocalPath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RemoteLastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ResolutionAction")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("ConflictLogs", "onedrive");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.DeltaToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriveName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("DeltaTokens", "onedrive");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.DiagnosticSettings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("LogLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("DiagnosticSettings", "onedrive");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.FileSystemItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriveItemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("LastSyncDirection")
                        .HasColumnType("integer");

                    b.Property<string>("LocalHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LocalModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocalPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParentItemId")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RemoteHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RemoteModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("FileSystemItems", "onedrive");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.SyncHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<int?>("ItemsDownloaded")
                        .HasColumnType("integer");

                    b.Property<int?>("ItemsUploaded")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SyncDirection")
                        .HasColumnType("integer");

                    b.Property<int>("SyncResult")
                        .HasColumnType("integer");

                    b.Property<int>("SyncType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("SyncHistory", "onedrive");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.ApplicationLog", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Sync.Client.Common.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.ConflictLog", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Sync.Client.Common.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.DeltaToken", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Sync.Client.Common.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.DiagnosticSettings", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Sync.Client.Common.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.FileSystemItem", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Sync.Client.Common.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Sync.Client.Common.Models.SyncHistory", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Sync.Client.Common.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
