namespace AStar.Dev.OneDrive.Sync.Client.Core.Models;

/// <summary>
///     Represents a debug log entry.
/// </summary>
/// <param name="Id">Unique identifier for the log entry.</param>
/// <param name="AccountId">Account ID associated with the log entry.</param>
/// <param name="Timestamp">When the log entry was created.</param>
/// <param name="LogLevel">Severity level (Info, Error, Entry, Exit).</param>
/// <param name="Source">Source of the log (typically ClassName.MethodName).</param>
/// <param name="Message">Log message content.</param>
/// <param name="Exception">Exception details if applicable.</param>
public sealed record DebugLogEntry(
    int Id,
    HashedAccountId AccountId,
    DateTimeOffset Timestamp,
    string LogLevel,
    string Source,
    string Message,
    string? Exception
);

public static class DebugLogEntryFactory
{
    extension(DebugLogEntry debugLogEntry)
    {
        /// <summary>
        /// Creates a new DebugLogEntry with the specified details. The Id is set to 0 and Timestamp is set to UtcNow, as these will typically be generated by the database upon insertion.
        /// </summary>
        /// <param name="hashedAccountId">The hashed account ID associated with the log entry.</param>
        /// <param name="source">The source of the log (typically ClassName.MethodName).</param>
        /// <param name="message">The log message content.</param>
        /// <param name="logLevel">The severity level of the log (Info, Error, Entry, Exit).</param>
        /// <param name="exception">Exception details if applicable.</param>
        /// <returns>A new DebugLogEntry instance.</returns>
        public static DebugLogEntry Create(HashedAccountId hashedAccountId, string source, string message, string logLevel = "Info", Exception? exception = null)
            => new(0, hashedAccountId, DateTimeOffset.UtcNow, logLevel, source, message, exception?.ToString());
    }
}
