// <auto-generated />
using System;
using AStar.Dev.OneDrive.Client.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStar.Dev.OneDrive.Client.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SyncDbContext))]
    [Migration("20260126153248_UpdateDebugLogs2")]
    partial class UpdateDebugLogs2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Data.Entities.AccountEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AutoSyncIntervalMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeltaToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableDebugLogging")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableDetailedSyncLogging")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAuthenticated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalSyncPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxItemsInBatch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxParallelUpDownloads")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId");

                    b.HasIndex("LocalSyncPath")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountId = "e29a2798-c836-4854-ac90-a3f2d37aae26",
                            AutoSyncIntervalMinutes = 0,
                            DisplayName = "System Admin",
                            EnableDebugLogging = true,
                            EnableDetailedSyncLogging = true,
                            IsAuthenticated = true,
                            LocalSyncPath = ".",
                            MaxItemsInBatch = 1,
                            MaxParallelUpDownloads = 1
                        });
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Data.Entities.DebugLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TimestampUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TimestampUtc_Ticks");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("DebugLogs", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Data.Entities.DriveItemEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CTag")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriveItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ETag")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastModifiedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastModifiedUtc_Ticks");

                    b.Property<int>("LastSyncDirection")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteHash")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DriveItemId");

                    b.HasIndex("IsFolder");

                    b.HasIndex("IsSelected");

                    b.HasIndex("AccountId", "RelativePath");

                    b.ToTable("DriveItems", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Data.Entities.FileOperationLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OneDriveId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Operation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncSessionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FileOperationLogs");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Data.Entities.SyncConflictEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DetectedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DetectedUtc_Ticks");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LocalModifiedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LocalModifiedUtc_Ticks");

                    b.Property<long>("LocalSize")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RemoteModifiedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RemoteModifiedUtc_Ticks");

                    b.Property<long>("RemoteSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResolutionStrategy")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountId", "IsResolved");

                    b.ToTable("SyncConflicts");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Data.Entities.SyncSessionLogEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConflictsDetected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilesUploaded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncSessionLogs");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Data.Entities.WindowPreferencesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(600.0);

                    b.Property<bool>("IsMaximized")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Width")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(800.0);

                    b.Property<double?>("X")
                        .HasColumnType("REAL");

                    b.Property<double?>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WindowPreferences");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Models.DeltaToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LastSyncedUtc")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastSyncedUtc_Ticks");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("DeltaTokens", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Data.Entities.DebugLogEntity", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Client.Core.Data.Entities.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Data.Entities.DriveItemEntity", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Client.Core.Data.Entities.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Data.Entities.SyncConflictEntity", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Client.Core.Data.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.OneDrive.Client.Core.Models.DeltaToken", b =>
                {
                    b.HasOne("AStar.Dev.OneDrive.Client.Core.Data.Entities.AccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
